### ISSUE TITLE
Next deployment (after 2024-02-01) to openflights.org

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1463]
Next major deployment after #1391, some items copied forward. 74539bd7ba067fbe9895977908dbf2ae6a885981 is deployed as of 2024-08-20.

- [ ] #1314 / 5e0fae7fa7d44e4414d3ea28b585da1bc5c2712b - Check and update `$GITHUB_ACCESS_TOKEN` if it's expired (it might not be, just the previous code update was rubbish in c03f72006444dfc2485eec28ba936d3d74d1631d).
  - May want to check the submission works afterwards too.
  - It might be necessary/useful to do #1171 too; add/create an `openflights-bot` user (or similar), and create a token on that account.
  - Maybe leave a comment in the `config.php` when the token is due to expire; as the newer token style only last a year.

TODOs:
- [ ] Add `en_GB` locale to `locale` table
  - #1404 - Make updating `locale` table easier; don't just want to run `sql/load-data.sql`. Split locale stuff into a new/separate/extra file so it can be run separately?
- [ ] Do we need to do any locale related regeneration server side? (Need more documentation here...)
- [ ] #1414
  - [ ] Update `route` table. [Data updated `2023-03-22`](http://arm.64hosts.com/).
    - Add `schedule` table schema to #1408.
    - Run `tools/update-arm.sh`.
    - Run `sql/import-arm.sql`.
    - Export updates routes to `data/routes.dat`.
 - [ ] #1435

---

Other fixes (missing files/crons):

- [ ] #1136 - Run `sql/top10.sql` and add/fix cron job.
- [ ] #1225 - Run `sql/update-demo.sql` and add/fix cron job.

---

Errors from logs that could do with investigating (or at least, logs posting on tasks):
- [ ] #1314
- [x] #1178
- [ ] #1483 (possible SQL errors?)

**Comment by joshleecreates** [comment]
What is that status on the tripit import? Can I help?

**Comment by reedy** [comment]
It needs logs from the server, so basically only one person with access to those unfortunately.

**Comment by TurnOffNOD** [comment]
What is the status of data(airports, airlines and routes) update?
